SELECT 
	DATE_TRUNC('week', DATE_TRUNC('month', CURRENT_DATE)) - INTERVAL '1 day' AS CALENDAR_BEGIN,
	DATE_TRUNC('week', DATE_TRUNC('month', CURRENT_DATE + INTERVAL '1 month') - INTERVAL '1 day' + INTERVAL '1 week')-INTERVAL '2 day' AS CALENDAR_END
