select TO_CHAR(DATE_TRUNC('WEEK', NOW() AT TIME ZONE 'Asia/Seoul'  + INTERVAL '1 DAYS')::DATE, 'YYYYMM')::INTEGER

select TO_CHAR(DATE_TRUNC('WEEK', NOW() AT TIME ZONE 'Asia/Seoul'  + INTERVAL '1 DAYS')::DATE, 'YYYYMMDD')::INTEGER
